/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.busNgayLamViec;
import BUS.busNhanVien;
import DTO.dtoNhanVien;
import DTO.dtoTaiKhoan;
import java.net.URL;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author NT
 */
public class jfrmManHinhChinh extends javax.swing.JFrame {

    private static dtoTaiKhoan TaiKhoanLogin = null;
    private static jfrmDonXinNghi jfrmDonXinNghi = null;
    private static jfrmDangKyLamThemGio jfrmdangKyLamThemGio = null;
    private static jfrmThongTinTaiKhoan jfrmthongTinTaiKhoan = null;
    private static jfrmDoiMatKhau jfrmdoiMatKhau = null;
    private static jfrmPhongBan jfrmphongBan = null;
    private static jfrmChucVu jfrmchucVu = null;
    private static jfrmThongKeHopDong jfrmhopDong = null;
    private static jfrmNhanVien jfrmnhanVien = null;
    private static jfrmDangKyLamThem jfrmDangKyLamThem = null;
    private static jfrmListDonXinNghi jfrmlistdonXinNghi = null;
    private static jfrmLapLuongNhanVien jfrmlapLuongNhanVien = null;
    private static jfrmThongKeChuyenCan jfrmThongKeChuyenCan = null;
    private static jfrmThongKeLuong jfrmThongKeLuong = null;
    private static jfrmThemHopDong jfrmthemHopDong = null;

    /**
     * Creates new form jfrmManHinhDangNhan
     */
    public jfrmManHinhChinh(dtoTaiKhoan taikhoan) {
        initComponents();
        this.TaiKhoanLogin = taikhoan;
        loadForm();
    }

    final void loadForm() {
        this.setLocationRelativeTo(null);
        URL iconURL = getClass().getResource("/IMG/Home-PNG-Pic.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());

    }

    private jfrmManHinhChinh() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    //Thay doi comp in fDeskTop
    private void loadComp(JInternalFrame comp) {
        boolean isTrung = false;
        for (JInternalFrame item : jdstMain.getAllFrames()) {
            if (item.getTitle().equals(comp.getTitle())) {
                isTrung = true;
            }
        }
        if (!isTrung) {
            jdstMain.add(comp);
        }
        
        jdstMain.setSelectedFrame(comp);
        comp.setVisible(false);
        int Locationx = (this.getSize().width / 2) - (comp.getSize().width / 2);
        comp.setLocation(Locationx - 5, 0);
        comp.setVisible(true);
        comp.getDesktopPane().getDesktopManager().deiconifyFrame(comp); 
        jdstMain.setSelectedFrame(comp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdstMain = new javax.swing.JDesktopPane();
        jmbChucNang = new javax.swing.JMenuBar();
        jmnChucNang = new javax.swing.JMenu();
        jmnDangKyThemGio = new javax.swing.JMenuItem();
        jmnLapDonXinNghi = new javax.swing.JMenuItem();
        jmnDiemCong = new javax.swing.JMenuItem();
        jmnLapLuongNhanVien = new javax.swing.JMenuItem();
        jmnQuanLy = new javax.swing.JMenu();
        jmnPhongBan = new javax.swing.JMenuItem();
        jmnChucVu = new javax.swing.JMenuItem();
        jmnThemHopDong = new javax.swing.JMenuItem();
        jmnNhanVien = new javax.swing.JMenuItem();
        jmnDangKyLamThem = new javax.swing.JMenuItem();
        jmnDonXinNghi = new javax.swing.JMenuItem();
        jmnBaoCaoThongKe = new javax.swing.JMenu();
        jmnChuyenCan = new javax.swing.JMenuItem();
        jmnLuongNhanVien = new javax.swing.JMenuItem();
        jmnHopDong = new javax.swing.JMenuItem();
        jmnTaiKhoan = new javax.swing.JMenu();
        jmnThongTinTaiKhoan = new javax.swing.JMenuItem();
        jmnDoiMatKhau = new javax.swing.JMenuItem();
        jmnThoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdstMain.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jdstMainHierarchyChanged(evt);
            }
        });

        javax.swing.GroupLayout jdstMainLayout = new javax.swing.GroupLayout(jdstMain);
        jdstMain.setLayout(jdstMainLayout);
        jdstMainLayout.setHorizontalGroup(
            jdstMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1042, Short.MAX_VALUE)
        );
        jdstMainLayout.setVerticalGroup(
            jdstMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        jmbChucNang.setToolTipText("n");
        jmbChucNang.setAutoscrolls(true);
        jmbChucNang.setMinimumSize(new java.awt.Dimension(0, 0));

        jmnChucNang.setText("Chức năng");

        jmnDangKyThemGio.setText("Đăng ký làm thêm giờ");
        jmnDangKyThemGio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnDangKyThemGioActionPerformed(evt);
            }
        });
        jmnChucNang.add(jmnDangKyThemGio);

        jmnLapDonXinNghi.setText("Lập đơn xin nghỉ");
        jmnLapDonXinNghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnLapDonXinNghiActionPerformed(evt);
            }
        });
        jmnChucNang.add(jmnLapDonXinNghi);

        jmnDiemCong.setText("Điểm công");
        jmnDiemCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnDiemCongActionPerformed(evt);
            }
        });
        jmnChucNang.add(jmnDiemCong);

        jmnLapLuongNhanVien.setText("Lập lương nhân viên");
        jmnLapLuongNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnLapLuongNhanVienActionPerformed(evt);
            }
        });
        jmnChucNang.add(jmnLapLuongNhanVien);

        jmbChucNang.add(jmnChucNang);

        jmnQuanLy.setText("Quản lý");

        jmnPhongBan.setText("Phòng ban");
        jmnPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnPhongBanActionPerformed(evt);
            }
        });
        jmnQuanLy.add(jmnPhongBan);

        jmnChucVu.setText("Chức vụ");
        jmnChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnChucVuActionPerformed(evt);
            }
        });
        jmnQuanLy.add(jmnChucVu);

        jmnThemHopDong.setText("Hợp đồng");
        jmnThemHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnThemHopDongActionPerformed(evt);
            }
        });
        jmnQuanLy.add(jmnThemHopDong);

        jmnNhanVien.setText("Nhân viên");
        jmnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnNhanVienActionPerformed(evt);
            }
        });
        jmnQuanLy.add(jmnNhanVien);

        jmnDangKyLamThem.setText("Đăng ký làm thêm");
        jmnDangKyLamThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnDangKyLamThemActionPerformed(evt);
            }
        });
        jmnQuanLy.add(jmnDangKyLamThem);

        jmnDonXinNghi.setText("Đơn xin nghỉ");
        jmnDonXinNghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnDonXinNghiActionPerformed(evt);
            }
        });
        jmnQuanLy.add(jmnDonXinNghi);

        jmbChucNang.add(jmnQuanLy);

        jmnBaoCaoThongKe.setText("Báo cáo - Thống kê");

        jmnChuyenCan.setText("Chuyên cần");
        jmnChuyenCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnChuyenCanActionPerformed(evt);
            }
        });
        jmnBaoCaoThongKe.add(jmnChuyenCan);

        jmnLuongNhanVien.setText("Lương nhân viên");
        jmnLuongNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnLuongNhanVienActionPerformed(evt);
            }
        });
        jmnBaoCaoThongKe.add(jmnLuongNhanVien);

        jmnHopDong.setText("Hợp đồng");
        jmnHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnHopDongActionPerformed(evt);
            }
        });
        jmnBaoCaoThongKe.add(jmnHopDong);

        jmbChucNang.add(jmnBaoCaoThongKe);

        jmnTaiKhoan.setText("Tài khoản");

        jmnThongTinTaiKhoan.setText("Thông tin tài khoản");
        jmnThongTinTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnThongTinTaiKhoanActionPerformed(evt);
            }
        });
        jmnTaiKhoan.add(jmnThongTinTaiKhoan);

        jmnDoiMatKhau.setText("Đổi mật khẩu");
        jmnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnDoiMatKhauActionPerformed(evt);
            }
        });
        jmnTaiKhoan.add(jmnDoiMatKhau);

        jmnThoat.setText("Thoát");
        jmnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnThoatActionPerformed(evt);
            }
        });
        jmnTaiKhoan.add(jmnThoat);

        jmbChucNang.add(jmnTaiKhoan);

        setJMenuBar(jmbChucNang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdstMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdstMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnDangKyThemGioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnDangKyThemGioActionPerformed
        if (jfrmdangKyLamThemGio == null) {
            jfrmdangKyLamThemGio = new jfrmDangKyLamThemGio(TaiKhoanLogin);
        }
        loadComp(jfrmdangKyLamThemGio);
    }//GEN-LAST:event_jmnDangKyThemGioActionPerformed

    private void jmnLapDonXinNghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnLapDonXinNghiActionPerformed
        if (jfrmDonXinNghi == null) {
            jfrmDonXinNghi = new jfrmDonXinNghi(TaiKhoanLogin);
        }
        loadComp(jfrmDonXinNghi);
    }//GEN-LAST:event_jmnLapDonXinNghiActionPerformed

    private void jmnDiemCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnDiemCongActionPerformed

        dtoNhanVien nhanVien = busNhanVien.getInstance().getNhanVientheoTaiKhoan(TaiKhoanLogin.getTAIKHOAN());
        if (!busNgayLamViec.getInstance().insertNgayLamViec(nhanVien.getMANV(), Calendar.getInstance().getTime())) {
            JOptionPane.showConfirmDialog(null, "Vui lòng kiểm tra lại!", "Thông báo", -1, 2);
            return;
        }
        JOptionPane.showConfirmDialog(null, "Chấm công thành công!", "Thông báo", -1, 1);
        return;
    }//GEN-LAST:event_jmnDiemCongActionPerformed

    private void jmnLapLuongNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnLapLuongNhanVienActionPerformed
        if (jfrmlapLuongNhanVien == null) {
            jfrmlapLuongNhanVien = new jfrmLapLuongNhanVien();
        }
        loadComp(jfrmlapLuongNhanVien);
    }//GEN-LAST:event_jmnLapLuongNhanVienActionPerformed

    private void jmnPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnPhongBanActionPerformed
        if (jfrmphongBan == null) {
            jfrmphongBan = new jfrmPhongBan();
        }
        loadComp(jfrmphongBan);
    }//GEN-LAST:event_jmnPhongBanActionPerformed

    private void jmnChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnChucVuActionPerformed
        if (jfrmchucVu == null) {
            jfrmchucVu = new jfrmChucVu();
        }
        loadComp(jfrmchucVu);
    }//GEN-LAST:event_jmnChucVuActionPerformed

    private void jmnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnNhanVienActionPerformed
        if (jfrmnhanVien == null) {
            jfrmnhanVien = new jfrmNhanVien();
        }
        loadComp(jfrmnhanVien);
    }//GEN-LAST:event_jmnNhanVienActionPerformed

    private void jmnThemHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnThemHopDongActionPerformed
        if (jfrmthemHopDong == null) {
            jfrmthemHopDong = new jfrmThemHopDong();
        }
        loadComp(jfrmthemHopDong);
    }//GEN-LAST:event_jmnThemHopDongActionPerformed

    private void jmnDangKyLamThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnDangKyLamThemActionPerformed
        if (jfrmDangKyLamThem == null) {
            jfrmDangKyLamThem = new jfrmDangKyLamThem();
        }
        loadComp(jfrmDangKyLamThem);
    }//GEN-LAST:event_jmnDangKyLamThemActionPerformed

    private void jmnDonXinNghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnDonXinNghiActionPerformed
        if (jfrmlistdonXinNghi == null) {
            jfrmlistdonXinNghi = new jfrmListDonXinNghi();
        }
        loadComp(jfrmlistdonXinNghi);
    }//GEN-LAST:event_jmnDonXinNghiActionPerformed

    private void jmnHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnHopDongActionPerformed
        if (jfrmhopDong == null) {
            jfrmhopDong = new jfrmThongKeHopDong();
        }
        loadComp(jfrmhopDong);
    }//GEN-LAST:event_jmnHopDongActionPerformed

    private void jmnThongTinTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnThongTinTaiKhoanActionPerformed
        if (jfrmthongTinTaiKhoan == null) {
            jfrmthongTinTaiKhoan = new jfrmThongTinTaiKhoan(TaiKhoanLogin);
        }
        loadComp(jfrmthongTinTaiKhoan);
    }//GEN-LAST:event_jmnThongTinTaiKhoanActionPerformed

    private void jmnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnDoiMatKhauActionPerformed

        if (jfrmdoiMatKhau == null) {
            jfrmdoiMatKhau = new jfrmDoiMatKhau(TaiKhoanLogin);
        }
        loadComp(jfrmdoiMatKhau);
    }//GEN-LAST:event_jmnDoiMatKhauActionPerformed

    private void jmnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jmnThoatActionPerformed

    private void jdstMainHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jdstMainHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jdstMainHierarchyChanged

    private void jmnChuyenCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnChuyenCanActionPerformed
        if (jfrmThongKeChuyenCan == null) {
            jfrmThongKeChuyenCan = new jfrmThongKeChuyenCan();
        }
        loadComp(jfrmThongKeChuyenCan);
    }//GEN-LAST:event_jmnChuyenCanActionPerformed

    private void jmnLuongNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnLuongNhanVienActionPerformed
        if (jfrmThongKeLuong == null) {
            jfrmThongKeLuong = new jfrmThongKeLuong();
        }
        loadComp(jfrmThongKeLuong);
    }//GEN-LAST:event_jmnLuongNhanVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmManHinhChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdstMain;
    private javax.swing.JMenuBar jmbChucNang;
    private javax.swing.JMenu jmnBaoCaoThongKe;
    private javax.swing.JMenu jmnChucNang;
    private javax.swing.JMenuItem jmnChucVu;
    private javax.swing.JMenuItem jmnChuyenCan;
    private javax.swing.JMenuItem jmnDangKyLamThem;
    private javax.swing.JMenuItem jmnDangKyThemGio;
    private javax.swing.JMenuItem jmnDiemCong;
    private javax.swing.JMenuItem jmnDoiMatKhau;
    private javax.swing.JMenuItem jmnDonXinNghi;
    private javax.swing.JMenuItem jmnHopDong;
    private javax.swing.JMenuItem jmnLapDonXinNghi;
    private javax.swing.JMenuItem jmnLapLuongNhanVien;
    private javax.swing.JMenuItem jmnLuongNhanVien;
    private javax.swing.JMenuItem jmnNhanVien;
    private javax.swing.JMenuItem jmnPhongBan;
    private javax.swing.JMenu jmnQuanLy;
    private javax.swing.JMenu jmnTaiKhoan;
    private javax.swing.JMenuItem jmnThemHopDong;
    private javax.swing.JMenuItem jmnThoat;
    private javax.swing.JMenuItem jmnThongTinTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
