/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.busNhanVien;
import DTO.dtoNhanVien;
import DTO.dtoTaiKhoan;
import javax.swing.JOptionPane;

/**
 *
 * @author NT
 */
public class jfrmThongTinTaiKhoan extends javax.swing.JInternalFrame {
//properties

    private dtoTaiKhoan TaiKhoanLogin = null;

    /**
     * Creates new form jfrmThongTinTaiKhoan
     */
    public jfrmThongTinTaiKhoan(dtoTaiKhoan taiKhoan) {
        initComponents();
        this.TaiKhoanLogin = taiKhoan;
    }
// Lấy thông tin nhân viên gán vào controls

    void LoadThongTin(dtoTaiKhoan TaiKhoan) {
        dtoNhanVien NhanVien = busNhanVien.getInstance().getNhanVientheoTaiKhoan(TaiKhoan.getTAIKHOAN());
        if(NhanVien==null)
        {
            JOptionPane.showConfirmDialog(null, "Không tìm thấy thông tin nhân viên!","Thông báo",-1,2);
            this.dispose();
        }
        jtxtMaNhanVien.setText(String.valueOf(NhanVien.getMANV()));
        jtxtHoTen.setText(String.valueOf(NhanVien.getTENNV()));
        jtxtSDT.setText(String.valueOf(NhanVien.getSDT()));
        jtxtDiaChi.setText(String.valueOf(NhanVien.getDiaChi()));
        jtxtTaiKhoan.setText(String.valueOf(NhanVien.getTAIKHOAN()));
        jtxtMaHopDong.setText(String.valueOf(NhanVien.getMAHD()));
        if (NhanVien.getGioiTinh() == 0) {
            jrdNu.setSelected(true);
        } else {
            jrdNam.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGioiTinh = new javax.swing.ButtonGroup();
        jtxtMaNhanVien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtHoTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jrdNam = new javax.swing.JRadioButton();
        jrdNu = new javax.swing.JRadioButton();
        jtxtSDT = new javax.swing.JTextField();
        jtxtDiaChi = new javax.swing.JTextField();
        jtxtTaiKhoan = new javax.swing.JTextField();
        jtxtMaHopDong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnCapNhat = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Thông tin nhân viên");
        setAutoscrolls(true);
        setVisible(true);
        addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                formHierarchyChanged(evt);
            }
        });

        jtxtMaNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtMaNhanVien.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mã nhân viên:");

        jtxtHoTen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Họ tên:");

        btnGroupGioiTinh.add(jrdNam);
        jrdNam.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jrdNam.setSelected(true);
        jrdNam.setText("Nam");

        btnGroupGioiTinh.add(jrdNu);
        jrdNu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jrdNu.setText("Nữ");

        jtxtSDT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtxtDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtxtTaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtTaiKhoan.setEnabled(false);

        jtxtMaHopDong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtMaHopDong.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Giới tính");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Địa chỉ:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Tai khoản:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Mã hợp đồng:");

        jbtnCapNhat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtnCapNhat.setText("Cập nhật");
        jbtnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jrdNam)
                                .addGap(28, 28, 28)
                                .addComponent(jrdNu))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jtxtHoTen))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(62, 62, 62)
                                        .addComponent(jtxtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(63, 63, 63)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxtDiaChi)
                                        .addComponent(jtxtTaiKhoan)
                                        .addComponent(jtxtMaHopDong)
                                        .addComponent(jtxtSDT)))))))
                .addGap(292, 292, 292))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdNam)
                    .addComponent(jrdNu)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMaHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jbtnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Cập nhật thông tin nhân viêm
    private void jbtnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCapNhatActionPerformed
        int MANV = Integer.parseInt(jtxtMaNhanVien.getText());
        String TenNV = jtxtHoTen.getText();
        String SDT = jtxtSDT.getText();
        String DiaChi = jtxtDiaChi.getText();
        String TaiKhoan = jtxtTaiKhoan.getText();
        int MAHD = Integer.parseInt(jtxtMaHopDong.getText());
        int GioiTinh = jrdNam.isSelected() == true ? 1 : 0;
        if(!busNhanVien.getInstance().updateNhanVien(MANV, TenNV, GioiTinh, SDT, DiaChi, TaiKhoan, MAHD))
        {
            JOptionPane.showConfirmDialog(null, "Vui lòng thực hiện lại!","Thông báo",-1,2);
        }
        else{
            JOptionPane.showConfirmDialog(null, "Cập nhật thành công!","Thông báo",-1,1);
        }

    }//GEN-LAST:event_jbtnCapNhatActionPerformed
//Load thông tin tài khoản
    private void formHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formHierarchyChanged
        LoadThongTin(TaiKhoanLogin);
    }//GEN-LAST:event_formHierarchyChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtnCapNhat;
    private javax.swing.JRadioButton jrdNam;
    private javax.swing.JRadioButton jrdNu;
    private javax.swing.JTextField jtxtDiaChi;
    private javax.swing.JTextField jtxtHoTen;
    private javax.swing.JTextField jtxtMaHopDong;
    private javax.swing.JTextField jtxtMaNhanVien;
    private javax.swing.JTextField jtxtSDT;
    private javax.swing.JTextField jtxtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
