/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.busChucVu;
import BUS.busHopDong;
import BUS.busNhanVien;
import BUS.busChamLuong;
import DTO.dtoChucVu;
import DTO.dtoHopDong;
import DTO.dtoNhanVien;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NT
 */
public class jfrmLapLuongNhanVien extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfrmLapLuongNhanVien
     */
    public jfrmLapLuongNhanVien() {
        initComponents();
        LoadDanhSachNhanVien();
        loadbinDing();
    }

    void LoadDanhSachNhanVien() {
        ArrayList<dtoNhanVien> list = busNhanVien.getInstance().getDanhSachNhanVien(jtxtXem.getText());
        DefaultTableModel model = (DefaultTableModel) jtbNhanVien.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        for (dtoNhanVien item : list) {
            dtoHopDong hopDong = busHopDong.getInstance().getHopDong(item.getMAHD());
            dtoChucVu chucVu = busChucVu.getInstance().getChucVu(hopDong.getMACV());
            model.addRow(new Object[]{item.getMANV(), item.getTENNV(), chucVu.getTenChucVu(), hopDong.getMAHD(), String.format("%.1f", hopDong.getTIENLUONG()), busChamLuong.getInstance().soNgayLamViec(item.getMANV()), busChamLuong.getInstance().soGioLamThem(item.getMANV()),String.format("%.1f",busChamLuong.getInstance().TinhLuong(item.getMANV()))});
        }
    }

    void loadbinDing() {
        jtbNhanVien.getSelectionModel().addListSelectionListener((e) -> {
            if (jtbNhanVien.getSelectedRow() >= 0) {
                Object MANV = jtbNhanVien.getValueAt(jtbNhanVien.getSelectedRow(), 0);
            }
        }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtxtXem = new javax.swing.JTextField();
        jbtnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbNhanVien = new javax.swing.JTable();
        btnTinhLuongAll = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Lập lương nhân viên");
        setAutoscrolls(true);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Tên Nhân viên");

        jtxtXem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtXem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jbtnSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtnSearch.setText("Xem");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jtbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Chức vụ", "Mã hợp đồng", "Hệ số lương", "Số ngày đi làm", "Số giờ làm thêm", "Tổng lương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbNhanVien);

        btnTinhLuongAll.setText("Tính lương");
        btnTinhLuongAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jtxtXem, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSearch)
                .addContainerGap(548, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTinhLuongAll)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtXem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTinhLuongAll)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        LoadDanhSachNhanVien();
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void btnTinhLuongAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongAllActionPerformed
        ArrayList<dtoNhanVien> list = busNhanVien.getInstance().getDanhSachNhanVien(jtxtXem.getText());
        for (dtoNhanVien item : list) {
            busChamLuong.getInstance().ChamLuongNhanVien(item.getMANV());
        }
        JOptionPane.showConfirmDialog(null, "Tính lương thành công!", "Thông báo", -1, 1);
        LoadDanhSachNhanVien();
    }//GEN-LAST:event_btnTinhLuongAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinhLuongAll;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JTable jtbNhanVien;
    private javax.swing.JTextField jtxtXem;
    // End of variables declaration//GEN-END:variables
}
