/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.busPhongBan;
import DTO.dtoPhongBan;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NT
 */
public class jfrmPhongBan extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfrmPhongBan
     */
    public jfrmPhongBan() {
        initComponents();
        loadBinding();
        jbtnXem.doClick();
    }
// LoadBingdings

    void loadBinding() {
        jtbPhongBan.getSelectionModel().addListSelectionListener((e) -> {
            try {
                if (jtbPhongBan.getSelectedRow() >= 0) {
                    Object MaPhong = jtbPhongBan.getValueAt(jtbPhongBan.getSelectedRow(), 0);
                    Object TenPhong = jtbPhongBan.getValueAt(jtbPhongBan.getSelectedRow(), 1);
                    Object DiaChi = jtbPhongBan.getValueAt(jtbPhongBan.getSelectedRow(), 2);
                    jtxtMaPB.setText(MaPhong.toString());
                    jtxtTenPB.setText(TenPhong.toString());
                    jtxtDiaChi.setText(DiaChi.toString());
                }

            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPhongBan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxtXem = new javax.swing.JTextField();
        jbtnXem = new javax.swing.JButton();
        jtxtTenPB = new javax.swing.JTextField();
        jtxtMaPB = new javax.swing.JTextField();
        jtxtDiaChi = new javax.swing.JTextField();
        jbtnXoa = new javax.swing.JButton();
        jbtnCapNhat = new javax.swing.JButton();
        jbtnThem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Phòng ban");
        setAutoscrolls(true);

        jtbPhongBan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtbPhongBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng ban", "Tên phòng ban", "Địa chỉ"
            }
        ));
        jtbPhongBan.setFillsViewportHeight(true);
        jtbPhongBan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtbPhongBan);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mã phòng ban:");

        jtxtXem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtXem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtXem.setNextFocusableComponent(jbtnXem);

        jbtnXem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtnXem.setText("Xem");
        jbtnXem.setNextFocusableComponent(jtxtMaPB);
        jbtnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXemActionPerformed(evt);
            }
        });

        jtxtTenPB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtTenPB.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jtxtMaPB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtMaPB.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtMaPB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMaPBKeyTyped(evt);
            }
        });

        jtxtDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtDiaChi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jbtnXoa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtnXoa.setText("Xóa");
        jbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaActionPerformed(evt);
            }
        });

        jbtnCapNhat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtnCapNhat.setText("Cập nhật");
        jbtnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCapNhatActionPerformed(evt);
            }
        });

        jbtnThem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtnThem.setText("Thêm");
        jbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Tên phòng ban:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Tên phòng ban:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Địa chỉ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(jtxtXem, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnXem)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtTenPB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtMaPB, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtXem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnXem)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtMaPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTenPB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Xem các phòng bang theo tên.
    private void jbtnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXemActionPerformed

        ArrayList<dtoPhongBan> listView=new ArrayList<>();
        listView.clear();
        DefaultTableModel model = (DefaultTableModel) jtbPhongBan.getModel();
        while(jtbPhongBan.getRowCount()>0) {
            model.removeRow(0);
        }
        String txtXem = jtxtXem.getText();
        if (txtXem.length() <= 0) {
            listView = busPhongBan.getInstance().getDanhSachPhongBan();
        } else {
            listView = busPhongBan.getInstance().getDanhSachPhongBan(txtXem);
        }

        for (dtoPhongBan iem : listView) {
            model.addRow(new Object[]{iem.getMAPB(), iem.getTenPB(), iem.getDiaChi()});
        }

    }//GEN-LAST:event_jbtnXemActionPerformed

//Thực hiện thêm phòng ban
    private void jbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemActionPerformed
        // TODO add your handling code here:
        if(jtxtMaPB.getText().length()<=0)return;
        int MaPhongBan = Integer.parseInt(jtxtMaPB.getText());
        String Ten = jtxtTenPB.getText();
        String DiaChi = jtxtDiaChi.getText();
        if(!busPhongBan.getInstance().insertPhongBan(MaPhongBan, Ten, DiaChi))
        {
            JOptionPane.showConfirmDialog(null, "Vui lòng thực hiện lại!","Thông báo",-1,2);
            return;
        }
        else
        {
            JOptionPane.showConfirmDialog(null, "Thêm thành công!","Thông báo",-1,1);
        }
        jbtnXem.doClick();
    }//GEN-LAST:event_jbtnThemActionPerformed

    private void jtxtMaPBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMaPBKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
        if(jtxtMaPB.getText().length()>=4)
        {
             evt.consume();
        }
    }//GEN-LAST:event_jtxtMaPBKeyTyped
//Thực hiện update thông tin nhân viên
    private void jbtnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCapNhatActionPerformed
        if(jtxtMaPB.getText().length()<=0)return;
        int MaPhongBan = Integer.parseInt(jtxtMaPB.getText());
        String Ten = jtxtTenPB.getText();
        String DiaChi = jtxtDiaChi.getText();
        if(!busPhongBan.getInstance().updatePhongBan(MaPhongBan, Ten, DiaChi))
        {
            JOptionPane.showConfirmDialog(null, "Vui lòng thực hiện lại!","Thông báo",-1,2);
            return;
        }
        else
        {
            JOptionPane.showConfirmDialog(null, "Cập nhật thành công!","Thông báo",-1,1);
        }
        jbtnXem.doClick();
    }//GEN-LAST:event_jbtnCapNhatActionPerformed
//Thực hiện xóa phog ban
    private void jbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaActionPerformed
        if(jtxtMaPB.getText().length()<=0)return;
        int MaPhongBan = Integer.parseInt(jtxtMaPB.getText());
        if(!busPhongBan.getInstance().deletePhongBan(MaPhongBan))
        {
            JOptionPane.showConfirmDialog(null, "Vui lòng thực hiện lại!","Thông báo",-1,2);
            return;
        }
        else
        {
            JOptionPane.showConfirmDialog(null, "Xóa thành công!","Thông báo",-1,1);
        }
        jbtnXem.doClick();
    }//GEN-LAST:event_jbtnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCapNhat;
    private javax.swing.JButton jbtnThem;
    private javax.swing.JButton jbtnXem;
    private javax.swing.JButton jbtnXoa;
    private javax.swing.JTable jtbPhongBan;
    private javax.swing.JTextField jtxtDiaChi;
    private javax.swing.JTextField jtxtMaPB;
    private javax.swing.JTextField jtxtTenPB;
    private javax.swing.JTextField jtxtXem;
    // End of variables declaration//GEN-END:variables
}
