/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.busTaiKhoan;
import DTO.dtoTaiKhoan;
import javax.swing.JOptionPane;

/**
 *
 * @author NT
 */
public class jfrmDoiMatKhau extends javax.swing.JInternalFrame {
//Properties
    private dtoTaiKhoan TaiKhoanLogin=null;
    /**
     * Creates new form jfrmDoiMatKhau
     */
    public jfrmDoiMatKhau(dtoTaiKhoan taiKhoan) {
        initComponents();
        TaiKhoanLogin=taiKhoan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnCapNhat = new javax.swing.JButton();
        jtxtMatKhauCu = new javax.swing.JPasswordField();
        jtxtMatKhauMoi = new javax.swing.JPasswordField();
        jtxtNhapLai = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cập nhật mật khẩu");
        setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mật khẩu củ:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Mật khẩu mới:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nhập lại mật khẩu mới:");

        jbtnCapNhat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtnCapNhat.setText("Cập nhật");
        jbtnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCapNhatActionPerformed(evt);
            }
        });

        jtxtMatKhauCu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtxtMatKhauMoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jtxtNhapLai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtMatKhauCu)
                            .addComponent(jtxtMatKhauMoi)
                            .addComponent(jtxtNhapLai, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(436, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Thực hiện cập nhật tài khoản
    private void jbtnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCapNhatActionPerformed
       String matKhauCu=jtxtMatKhauCu.getText();
       String matKhauMoi=jtxtMatKhauMoi.getText();
       String preMatKhauMoi = jtxtNhapLai.getText();
       if(matKhauCu.length()==0||matKhauMoi.length()==0||preMatKhauMoi.length()==0)
       {
           JOptionPane.showConfirmDialog(null, "Vui lòng nhập đầy đủ thông tin!","Thông báo",-1,2);
           return;
       }
       dtoTaiKhoan taiKhoan = busTaiKhoan.getInstance().layThongTinTaiKhoan(TaiKhoanLogin.getTAIKHOAN());
       if(!matKhauCu.equals(taiKhoan.getMATKHAU()))
       {
           JOptionPane.showConfirmDialog(null, "Mật khẩu củ sai!","Thông báo",-1,2);
           return;
       }
       if(!matKhauMoi.equals(preMatKhauMoi))
       {
           JOptionPane.showConfirmDialog(null, "Mật khẩu mới không trùng nhau!","Thông báo",-1,2);
           return;
       }
       if(!busTaiKhoan.getInstance().updateTaiKhoan(taiKhoan.getTAIKHOAN(),matKhauMoi, taiKhoan.getLV()))
       {
           JOptionPane.showConfirmDialog(null, "Vui lòng thực hiện lại!","Thông báo",-1,2);
           return;
       }
       else
       {
           JOptionPane.showConfirmDialog(null, "Cập nhật thành công!","Thông báo",-1,1);
           return;
       }
       
    }//GEN-LAST:event_jbtnCapNhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnCapNhat;
    private javax.swing.JPasswordField jtxtMatKhauCu;
    private javax.swing.JPasswordField jtxtMatKhauMoi;
    private javax.swing.JPasswordField jtxtNhapLai;
    // End of variables declaration//GEN-END:variables
}
