/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.busDonXinNghi;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import DTO.dtoDonXinNghi;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NT
 */
public class jfrmListDonXinNghi extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfrmListDonXinNghi
     */
    public jfrmListDonXinNghi() {
        initComponents();
        jdtpkTuNgay.setDate(Calendar.getInstance().getTime());
        loadDonXinNghi();
        loadbinDing();
    }
//load binding

    void loadbinDing() {
        jtbDonXinNghi.getSelectionModel().addListSelectionListener((e) -> {
            if (jtbDonXinNghi.getSelectedRow() >= 0) {
                Object madon = jtbDonXinNghi.getValueAt(jtbDonXinNghi.getSelectedRow(), 0);
                Object lydo = jtbDonXinNghi.getValueAt(jtbDonXinNghi.getSelectedRow(), 5);
                Object thoigianlap = jtbDonXinNghi.getValueAt(jtbDonXinNghi.getSelectedRow(), 2);
                Object thoigianbatdau = jtbDonXinNghi.getValueAt(jtbDonXinNghi.getSelectedRow(), 3);
                Object thoigianketthuc = jtbDonXinNghi.getValueAt(jtbDonXinNghi.getSelectedRow(), 4);
                Object manv = jtbDonXinNghi.getValueAt(jtbDonXinNghi.getSelectedRow(), 1);
                jtxtMa.setText(madon.toString());
                jtxtLyDo.setText(lydo.toString());
                jtxtThoiGianLap.setText(thoigianlap.toString());
                jtxtTuNgay.setText(thoigianbatdau.toString());
                jtxtDenNgay.setText(thoigianketthuc.toString());
                jtxtNhanVien.setText(manv.toString());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtMa = new javax.swing.JTextField();
        jtxtNhanVien = new javax.swing.JTextField();
        jtxtThoiGianLap = new javax.swing.JTextField();
        jtxtTuNgay = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtLyDo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtDenNgay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDonXinNghi = new javax.swing.JTable();
        jdtpkTuNgay = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        jbtnXem = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Danh sách đơn xin nghỉ");
        setAutoscrolls(true);

        jtxtMa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtMa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtMa.setEnabled(false);

        jtxtNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtNhanVien.setEnabled(false);

        jtxtThoiGianLap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtThoiGianLap.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtThoiGianLap.setEnabled(false);

        jtxtTuNgay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtTuNgay.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtTuNgay.setEnabled(false);

        jtxtLyDo.setColumns(20);
        jtxtLyDo.setRows(5);
        jtxtLyDo.setEnabled(false);
        jScrollPane2.setViewportView(jtxtLyDo);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Mã:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Nhân viên:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Thời gian lập:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Từ ngày:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Đến ngày:");

        jtxtDenNgay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtxtDenNgay.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtDenNgay.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Lý do:");

        jtbDonXinNghi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Nhân viên", "ThoiGianLap", "Tungay", "denngay", "Lý do"
            }
        ));
        jtbDonXinNghi.setFillsViewportHeight(true);
        jtbDonXinNghi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtbDonXinNghi);
        if (jtbDonXinNghi.getColumnModel().getColumnCount() > 0) {
            jtbDonXinNghi.getColumnModel().getColumn(2).setMinWidth(0);
            jtbDonXinNghi.getColumnModel().getColumn(2).setPreferredWidth(0);
            jtbDonXinNghi.getColumnModel().getColumn(2).setMaxWidth(0);
            jtbDonXinNghi.getColumnModel().getColumn(3).setMinWidth(0);
            jtbDonXinNghi.getColumnModel().getColumn(3).setPreferredWidth(0);
            jtbDonXinNghi.getColumnModel().getColumn(3).setMaxWidth(0);
            jtbDonXinNghi.getColumnModel().getColumn(4).setMinWidth(0);
            jtbDonXinNghi.getColumnModel().getColumn(4).setPreferredWidth(0);
            jtbDonXinNghi.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        jdtpkTuNgay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jdtpkTuNgay.setFormats("dd/MM/yyyy");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Từ ngày:");

        jbtnXem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jbtnXem.setText("Xem");
        jbtnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtTuNgay)
                                    .addComponent(jtxtMa)
                                    .addComponent(jtxtNhanVien, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtThoiGianLap, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtDenNgay)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jdtpkTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnXem)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdtpkTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jbtnXem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtThoiGianLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtxtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Load danh sách đơn xin nghĩ theo ngày!
    private void jbtnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXemActionPerformed
        loadDonXinNghi();
    }//GEN-LAST:event_jbtnXemActionPerformed
    //load don xin nghi tu ngay bat dau
    void loadDonXinNghi() {
        DefaultTableModel model = (DefaultTableModel) jtbDonXinNghi.getModel();
        while (jtbDonXinNghi.getRowCount() > 0) {
            model.removeRow(0);

        }
        Date date = jdtpkTuNgay.getDate();
        ArrayList<dtoDonXinNghi> list = busDonXinNghi.getInstance().getListDonXinNgi(date);
        for (dtoDonXinNghi item : list) {
            model.addRow(new Object[]{item.getMADON(), item.getMANV(), item.getThoiGianLap(), item.getThoiGianBatDau(), item.getThoiGianKetThuc(), item.getLYDO()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnXem;
    private org.jdesktop.swingx.JXDatePicker jdtpkTuNgay;
    private javax.swing.JTable jtbDonXinNghi;
    private javax.swing.JTextField jtxtDenNgay;
    private javax.swing.JTextArea jtxtLyDo;
    private javax.swing.JTextField jtxtMa;
    private javax.swing.JTextField jtxtNhanVien;
    private javax.swing.JTextField jtxtThoiGianLap;
    private javax.swing.JTextField jtxtTuNgay;
    // End of variables declaration//GEN-END:variables
}
